#!/bin/bash
#      _ _     _   _ _ _
#     | (_)   | | (_) | |
#   __| |_ ___| |_ _| | | ___ _ __
#  / _` | / __| __| | | |/ _ \ '__|
# | (_| | \__ \ |_| | | |  __/ |
#  \__,_|_|___/\__|_|_|_|\___|_|
#
# Generated by distiller
#
#SBATCH --qos=realtime
#SBATCH --constraint=cpu
#SBATCH --nodes=4
#SBATCH --time=02:00:00
#SBATCH --exclusive
#SBATCH --account=m3795
#SBATCH --chdir=/pscratch/sd/s/swelborn/test-stempy-overhead
#SBATCH --image=openchemistry/stempy-mpi:latest

export HDF5_USE_FILE_LOCKING=FALSE

run_scans() {
    local start_scan=$1
    local end_scan=$2
    local start_distiller=$3
    local data_dir=$4
    local image_version=$5
    local num_runs=$6

    for (( scan=start_scan; scan<=end_scan; scan++ )); do
        local distiller=$((start_distiller + scan - start_scan))
        echo "======================================================"
        echo "Starting scans for scan number $scan..."
        for (( run=0; run<num_runs; run++ )); do
            echo "Run $run of scan $scan..."
            srun --exclusive -c 128 -n 4 shifter python3 /pscratch/sd/s/swelborn/test-stempy-overhead/count.py --pad -l $data_dir -t 4.5 -s $scan -d $distiller -z $image_version --multi-pass || error_exit "Error shifter execution failed."
        done
        echo "======================================================"
    done
}

DATA_DIR="/pscratch/sd/s/swelborn/test-stempy-overhead/test-real-data"
IMAGE="stempy-mpi-3.3.14"
NUM_RUNS=5

# First batch of real data
run_scans 14 25 16075 $DATA_DIR $IMAGE $NUM_RUNS

# Second batch of real data (discontinuity in distiller IDs)
run_scans 26 29 16091 $DATA_DIR $IMAGE $NUM_RUNS

# Blank data
DATA_DIR="/pscratch/sd/s/swelborn/test-stempy-overhead/test-blank-data"
run_scans 93 96 16162 $DATA_DIR $IMAGE $NUM_RUNS